package bns.a6.microui.api.enums;

public enum ServiceNames {

    CUSTOMERTOACCOUNTRELATIONSHIP,
    CUSTOMERPROFILE,
    IDENTIFICATION,
    EMPLOYMENT,
    CONTACTMETHOD,
    CUSTOMERSEARCH,
    CUSTOMERLOOKUP,
    COUNTRYCODEREFERENCE,
    INTENTOFUSE,
    ACCOUNTPROFILE
}
